export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST"
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS"
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL"

export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET"

export const ORDER_DETAIL_REQUEST = "ORDER_DETAIL_REQUEST"
export const ORDER_DETAIL_SUCCESS = "ORDER_DETAIL_SUCCESS"
export const ORDER_DETAIL_FAIL = "ORDER_DETAIL_FAIL"


export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST"
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS"
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL"
export const ORDER_PAY_RESET = "ORDER_PAY_RESET"

export const ORDER_LIST_ADMIN_REQUEST = "ORDER_LIST_ADMIN_REQUEST"
export const ORDER_LIST_ADMIN_SUCCESS = "ORDER_LIST_ADMIN_SUCCESS"
export const ORDER_LIST_ADMIN_FAIL = "ORDER_LIST_ADMIN_FAIL"
export const ORDER_LIST_ADMIN_RESET = "ORDER_LIST_ADMIN_RESET"


export const MY_ORDER_REQUEST = "MY_ORDER_REQUEST"
export const MY_ORDER_SUCCESS = "MY_ORDER_SUCCESS"
export const MY_ORDER_FAIL = "MY_ORDER_FAIL"
export const MY_ORDER_RESET = "MY_ORDER_RESET"


export const ORDER_TO_DELIVERED_REQUEST = "ORDER_TO_DELIVERED_REQUEST"
export const ORDER_TO_DELIVERED_SUCCESS = "ORDER_TO_DELIVERED_SUCCESS"
export const ORDER_TO_DELIVERED_FAIL = "ORDER_TO_DELIVERED_FAIL"
export const ORDER_TO_DELIVERED_RESET = "ORDER_TO_DELIVERED_RESET"