export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST"
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS"
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL"

export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET"

export const ORDER_GET_BY_ID_REQUEST = "ORDER_GET_BY_ID_REQUEST"
export const ORDER_GET_BY_ID_SUCCESS = "ORDER_GET_BY_ID_SUCCESS"
export const ORDER_GET_BY_ID_FAIL = "ORDER_GET_BY_ID_FAIL"
